### ISSUE TITLE
How to upgrade to 1.6?

### ISSUE THREAD

**Issue by pcastellazzi** [psiberx/cp2077-respector#3]
It looks like to upgrade respector to work with 1.6 a file named `tweakdb-strings.txt` [1] should be made available containing all the in game items.

Can you provide a sample and some general pointers to do the upgrade correctly?

[1] https://github.com/psiberx/cp2077-respector/blob/main/mod/Compiler.lua#L25

**Comment by psiberx** [comment]
You can find strings on discord https://discord.gg/wZHqnh6z
Unfortunately the part for updating items is only 20% automated. You can collect base info with names and descriptions, but after that you have to analyze and manually edit the spreadsheet in `mod/data/` to generate the new database.
